/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vie Dinh (https://sketchfab.com/yenvydinh2295)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sushi-bar-f699052fd5d7428ca67ba8e84afa1246
Title: Sushi Bar
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import sushiScene from "../assets/3d/sushi_bar.glb";
import { a } from "@react-spring/three";

const Sushi = ({ props }) => {
  const { nodes, materials } = useGLTF(sushiScene);
  return (
    <a.group {...props}>
      {/* <group rotation={[-Math.PI / 2, 0, 0]}> */}
      <mesh
        geometry={nodes.Plane006_0.geometry}
        material={materials.Sushi_Bar}
      />
      <mesh
        geometry={nodes.Plane001_0.geometry}
        material={materials.Sushi_Bar}
      />
      <mesh
        geometry={nodes.Plane002_0.geometry}
        material={materials.Sushi_Bar}
        position={[0.06, 2.197, 0.742]}
        scale={[1, 1.097, 1]}
      />
      <mesh
        geometry={nodes.Plane003_0.geometry}
        material={materials.Sushi_Bar}
        position={[0.06, 2.197, 0.742]}
        scale={[1, 1.097, 1]}
      />
      <mesh
        geometry={nodes.Plane004_0.geometry}
        material={materials.Sushi_Bar}
        position={[0.06, 2.197, 0.742]}
        scale={[1, 1.097, 1]}
      />
      <mesh
        geometry={nodes.Plane005_0.geometry}
        material={materials.Sushi_Bar}
        position={[0.06, 2.197, 0.742]}
        scale={[1, 1.097, 1]}
      />
      <mesh
        geometry={nodes.Plane011_0.geometry}
        material={materials.Sushi_Bar}
        position={[0.06, 2.197, 0.742]}
        scale={[1, 1.097, 1]}
      />
      <mesh
        geometry={nodes.Plane040_0.geometry}
        material={materials.Sushi_Bar}
        position={[-1.151, -0.551, 1.111]}
        rotation={[0.534, -0.304, -0.965]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0.geometry}
        material={materials.Sushi_Bar}
        position={[-0.695, -0.712, 1.142]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane017_0.geometry}
        material={materials.Sushi_Bar}
        position={[-1.483, -0.211, 1.143]}
        rotation={[0.146, -0.126, 1.146]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane017_0_1.geometry}
        material={materials.Sushi_Bar}
        position={[-1.019, -0.134, 1.143]}
        rotation={[0, 0.419, -0.397]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_1.geometry}
        material={materials.Sushi_Bar}
        position={[-1.558, 0.148, 1.044]}
        rotation={[-0.111, -0.598, -2.262]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_1.geometry}
        material={materials.Sushi_Bar}
        position={[-1.164, 0.094, 1.161]}
        rotation={[-0.431, 0.252, 0.806]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_2.geometry}
        material={materials.Sushi_Bar}
        position={[-1.322, 0.519, 1.126]}
        rotation={[-0.603, -0.068, 2.745]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane017_0_2.geometry}
        material={materials.Sushi_Bar}
        position={[-0.803, 0.351, 1.218]}
        rotation={[0, 0.477, 0]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_3.geometry}
        material={materials.Sushi_Bar}
        position={[-0.915, 0.645, 0.991]}
        rotation={[-0.63, -0.509, -2.998]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_4.geometry}
        material={materials.Sushi_Bar}
        position={[-0.596, -0.042, 1.258]}
        rotation={[0.099, -0.078, -2.656]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_5.geometry}
        material={materials.Sushi_Bar}
        position={[-0.783, -0.379, 1.347]}
        rotation={[0.21, -0.808, -2.421]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_6.geometry}
        material={materials.Sushi_Bar}
        position={[-0.528, 0.692, 1.108]}
        rotation={[-0.079, -0.245, 1.682]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_2.geometry}
        material={materials.Sushi_Bar}
        position={[-0.311, -0.396, 1.175]}
        rotation={[0.603, -0.163, -0.085]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_3.geometry}
        material={materials.Sushi_Bar}
        position={[-0.216, -0.71, 0.993]}
        rotation={[0.181, 0.19, -1.367]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_7.geometry}
        material={materials.Sushi_Bar}
        position={[-0.379, 0.29, 1.286]}
        rotation={[-0.603, -0.068, 2.745]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_8.geometry}
        material={materials.Sushi_Bar}
        position={[-0.144, -0.024, 1.257]}
        rotation={[-0.734, -0.242, 1.593]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_9.geometry}
        material={materials.Sushi_Bar}
        position={[-0.097, 0.701, 1.189]}
        rotation={[-0.046, -0.613, -2.717]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_4.geometry}
        material={materials.Sushi_Bar}
        position={[0.01, 0.349, 1.231]}
        rotation={[0.181, 0.19, -1.367]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_5.geometry}
        material={materials.Sushi_Bar}
        position={[0.131, -0.417, 1.215]}
        rotation={[0.182, 0.1, -0.515]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_6.geometry}
        material={materials.Sushi_Bar}
        position={[0.177, -0.722, 0.98]}
        rotation={[0.501, -0.138, -0.37]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_10.geometry}
        material={materials.Sushi_Bar}
        position={[0.375, 0.652, 1.046]}
        rotation={[-0.292, -0.383, 1.303]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_7.geometry}
        material={materials.Sushi_Bar}
        position={[0.283, 0.013, 1.323]}
        rotation={[0.125, -0.087, 1.163]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_8.geometry}
        material={materials.Sushi_Bar}
        position={[0.532, -0.262, 1.118]}
        rotation={[0.287, -0.307, -0.283]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_9.geometry}
        material={materials.Sushi_Bar}
        position={[0.473, 0.347, 1.301]}
        rotation={[0.237, -0.679, -2.409]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_10.geometry}
        material={materials.Sushi_Bar}
        position={[0.587, -0.64, 0.991]}
        rotation={[0.252, 0.3, -0.79]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_11.geometry}
        material={materials.Sushi_Bar}
        position={[0.814, 0.555, 1.132]}
        rotation={[-0.122, 0.378, 2.004]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_11.geometry}
        material={materials.Sushi_Bar}
        position={[0.758, 0.103, 1.223]}
        rotation={[0.27, 0.418, 0.238]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_12.geometry}
        material={materials.Sushi_Bar}
        position={[0.908, -0.226, 1.042]}
        rotation={[0.278, 0.182, -0.666]}
        scale={1.127}
      />
      <mesh
        geometry={nodes.Plane043_0_13.geometry}
        material={materials.Sushi_Bar}
        position={[1.227, 0.114, 1.035]}
        rotation={[0.252, 0.3, -0.79]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane040_0_12.geometry}
        material={materials.Sushi_Bar}
        position={[1.186, 0.409, 1.233]}
        rotation={[-0.566, -0.186, 1.38]}
        scale={1.203}
      />
      <mesh
        geometry={nodes.Plane043_0_14.geometry}
        material={materials.Sushi_Bar}
        position={[1.329, -0.231, 1.155]}
        rotation={[0.221, 0.078, -0.568]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_15.geometry}
        material={materials.Sushi_Bar}
        position={[1.065, -0.473, 1.119]}
        rotation={[0.597, 0.264, -0.834]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane043_0_16.geometry}
        material={materials.Sushi_Bar}
        position={[1.097, -0.069, 1.389]}
        rotation={[0.597, 0.264, -0.834]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.Plane_0.geometry}
        material={materials.Sushi_Bar}
        scale={[2.997, 4.254, 4.254]}
      />
      <mesh
        geometry={nodes.Plane007_0.geometry}
        material={materials.Sushi_Bar}
        position={[0, 0, -0.255]}
        scale={[2.997, 4.254, 4.254]}
      />
      {/* </group> */}
    </a.group>
  );
};

export default Sushi;
